version: '2'

services:

### PHP-FPM Container #######################################

    php-fpm:
        build:
            context: ./php-fpm
            dockerfile: Dockerfile-70
        volumes_from:
            - application
        expose:
            - "9000"
        links:
            - workspace

### Laravel Application Code Container ######################

    application:
        build: ./application
        volumes:
            - ../site/:/var/www/laravel

### Databases Data Container ################################

    data:
        build: ./data
        volumes:
            - /var/lib/postgres:/var/lib/postgres

### Nginx Server Container ##################################

    nginx:
        build: ./nginx
        volumes_from:
            - application
        volumes:
            - ./logs/nginx/:/var/log/nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm

### PostgreSQL Container ####################################

    postgres:
        build: ./postgres
        volumes_from:
            - data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: homestead
            POSTGRES_USER: homestead
            POSTGRES_PASSWORD: secret

### Workspace Utilities Container ###########################

    workspace:
        build: ./workspace
        volumes_from:
            - application
        tty: true

### Add more Containers below ###############################
